version: "3"

services:
  app:
    image: drakona/php:8.2-symfony
    depends_on:
      - db
    volumes:
      - .:/srv

  nginx:
    image: drakona/nginx:8-symfony
    depends_on:
      - app
    volumes:
      - .:/srv
    ports:
      - "8000:80"

  db:
    image: mariadb:10
    environment:
      MARIADB_ROOT_PASSWORD: pass
      MARIADB_DATABASE: api
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"

  mailhog:
    image: mailhog/mailhog
    logging:
      driver: 'none'
    ports:
      - '8025:8025'
      - '1025:1025'

###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
  db-data: {}
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
